import React, { useState } from "react";
import { Link } from "react-router-dom";
import "./Examples.css";

const EXAMPLE_BOOKS = [
  {
    id: "wordo",
    title: "Wordo — Default Sample",
    file: "Wordo.pdf",
    desc: "The default BOOP sample book, generated with standard settings. Uses the default cover and background images bundled with the generator.",
    difficulty: "Mixed",
    pages: 4,
    topics: 2,
    puzzles: { normal: 3, hard: 2, bonus: 1 },
    cover: "Wordo_cover.png",
    hasCustomCover: true,
  },
  {
    id: "sports-games",
    title: "Sports & Games",
    file: "Sports_and_Games.pdf",
    desc: "A single-theme book with mixed difficulty levels. Features football, basketball, tennis, swimming and more — with normal, hard, and bonus puzzles.",
    difficulty: "Mixed",
    pages: 4,
    topics: 1,
    puzzles: { normal: 3, hard: 2, bonus: 2 },
    cover: "sports_cover.jpg",
  },
  {
    id: "science-wildlife",
    title: "Science & Wildlife",
    file: "Science_and_Wildlife.pdf",
    desc: "Two topics combined in one book. Explore science (atoms, cells, genes) and wildlife (elephants, tigers, bears) across normal and hard puzzles.",
    difficulty: "Normal",
    pages: 3,
    topics: 2,
    puzzles: { normal: 2, hard: 1, bonus: 0 },
    cover: "nature_cover.jpg",
  },
  {
    id: "cultural-journey",
    title: "Cultural Journey",
    file: "Cultural_Journey.pdf",
    desc: "A hard-mode-only book exploring music, dance, literature, and world heritage. Includes bonus puzzles for extra challenge.",
    difficulty: "Hard",
    pages: 4,
    topics: 1,
    puzzles: { normal: 0, hard: 3, bonus: 1 },
    cover: "culture_cover.jpg",
  },
  {
    id: "astronomy",
    title: "Astronomy Explorer",
    file: "Astronomy_Explorer.pdf",
    desc: "Focus on bonus circular puzzles alongside normal grids. Stars, planets, galaxies, and cosmic vocabulary await.",
    difficulty: "Bonus",
    pages: 4,
    topics: 1,
    puzzles: { normal: 2, hard: 0, bonus: 2 },
    cover: "space_cover.jpg",
  },
  {
    id: "mega-book",
    title: "Mega Puzzle Book",
    file: "Mega_Puzzle_Book.pdf",
    desc: "Our biggest example — all five topics across every difficulty level. 20 puzzles total including bonus rounds.",
    difficulty: "Mixed",
    pages: 6,
    topics: 5,
    puzzles: { normal: 10, hard: 5, bonus: 5 },
    cover: "mixed_cover.jpg",
  },
  {
    id: "sports-deluxe",
    title: "Sports Deluxe",
    file: "Sports_Deluxe.pdf",
    desc: "Sports puzzles with a custom cover image and themed backgrounds. Shows how uploaded images enhance your book.",
    difficulty: "Mixed",
    pages: 4,
    topics: 1,
    puzzles: { normal: 2, hard: 1, bonus: 1 },
    cover: "sports_cover.jpg",
    hasCustomCover: true,
  },
  {
    id: "nature-explorer",
    title: "Nature Explorer",
    file: "Nature_Explorer.pdf",
    desc: "Wildlife-themed book with a nature cover and custom background on title pages. Shows background image support.",
    difficulty: "Normal",
    pages: 3,
    topics: 1,
    puzzles: { normal: 2, hard: 1, bonus: 0 },
    cover: "nature_cover.jpg",
    hasCustomCover: true,
  },
  {
    id: "mixed-collection",
    title: "Mixed Collection",
    file: "Mixed_Collection.pdf",
    desc: "Three topics (science, culture, astronomy) with custom cover. Demonstrates multi-topic single-puzzle books.",
    difficulty: "Mixed",
    pages: 3,
    topics: 3,
    puzzles: { normal: 3, hard: 3, bonus: 0 },
    cover: "mixed_cover.jpg",
    hasCustomCover: true,
  },
];

const formatPuzzles = (p) => {
  const parts = [];
  if (p.normal) parts.push(`${p.normal} normal`);
  if (p.hard) parts.push(`${p.hard} hard`);
  if (p.bonus) parts.push(`${p.bonus} bonus`);
  return parts.join(", ");
};

const getFileUrl = (filename) =>
  `${process.env.PUBLIC_URL || ""}/examples/${filename}`;

const Examples = () => {
  const [activeBook, setActiveBook] = useState(EXAMPLE_BOOKS[0]);

  return (
    <div className="examples-page">
      <div className="container">
        <div className="examples-header">
          <h1>Sample Puzzle Books</h1>
          <p className="examples-subtitle">
            Browse sample PDF puzzle books generated by BOOP. The Wordo sample
            uses the default cover and background images bundled with the generator.
          </p>
        </div>

        <div className="examples-layout">
          <div className="examples-viewer">
            <iframe
              src={getFileUrl(activeBook.file)}
              title={activeBook.title}
              className="pdf-viewer-iframe"
            />
          </div>
          <div className="examples-info">
            <h2 className="examples-book-title">{activeBook.title}</h2>
            <span
              className="examples-diff-badge"
              style={{
                background:
                  activeBook.difficulty === "Hard"
                    ? "#8B3A3A"
                    : activeBook.difficulty === "Mixed"
                    ? "#C49464"
                    : activeBook.difficulty === "Bonus"
                    ? "#4A6FA5"
                    : "#3D6B3D",
              }}
            >
              {activeBook.difficulty}
            </span>
            <p className="examples-book-desc">{activeBook.desc}</p>

            <div className="examples-specs">
              <div className="examples-spec">
                <span className="spec-value">{activeBook.pages}</span>
                <span className="spec-label">Sections</span>
              </div>
              <div className="examples-spec">
                <span className="spec-value">{activeBook.topics}</span>
                <span className="spec-label">Topics</span>
              </div>
              <div className="examples-spec">
                <span className="spec-value">
                  {(activeBook.puzzles.normal || 0) +
                    (activeBook.puzzles.hard || 0) +
                    (activeBook.puzzles.bonus || 0)}
                </span>
                <span className="spec-label">Puzzles</span>
              </div>
            </div>

            <div className="examples-breakdown">
              <h4>Puzzle Breakdown</h4>
              <ul className="breakdown-list">
                {activeBook.puzzles.normal > 0 && (
                  <li>
                    <span className="breakdown-dot" style={{background:"#3D6B3D"}} />
                    {activeBook.puzzles.normal} Normal
                  </li>
                )}
                {activeBook.puzzles.hard > 0 && (
                  <li>
                    <span className="breakdown-dot" style={{background:"#8B3A3A"}} />
                    {activeBook.puzzles.hard} Hard
                  </li>
                )}
                {activeBook.puzzles.bonus > 0 && (
                  <li>
                    <span className="breakdown-dot" style={{background:"#4A6FA5"}} />
                    {activeBook.puzzles.bonus} Bonus
                  </li>
                )}
              </ul>
            </div>

            {activeBook.hasCustomCover && (
              <div className="examples-feature-badge">
                Custom cover &amp; background images
              </div>
            )}

            <div className="examples-cta">
              <p>Create your own puzzle book with these settings.</p>
              <Link to="/create" className="btn btn-primary btn-lg">
                Create Your Book
              </Link>
            </div>
          </div>
        </div>

        <section className="examples-all">
          <h2 className="section-heading">
            <span className="heading-ornament">&#10022;</span>
            All Example Files
            <span className="heading-ornament">&#10022;</span>
          </h2>
          <div className="all-examples-grid">
            {EXAMPLE_BOOKS.map((book) => (
              <div
                key={book.id}
                className={`all-example-card${activeBook.id === book.id ? " active" : ""}`}
                onClick={() => setActiveBook(book)}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); setActiveBook(book); } }}
              >
                <div className="all-example-img-wrap">
                  <img
                    src={getFileUrl(book.cover)}
                    alt=""
                    className="all-example-img"
                    onError={(e) => {
                      e.target.style.display = "none";
                    }}
                  />
                </div>
                <div className="all-example-info">
                  <h4>{book.title}</h4>
                  <span className="all-example-diff">{book.difficulty}</span>
                  <p>{formatPuzzles(book.puzzles)}</p>
                  <a
                    href={getFileUrl(book.file)}
                    className="btn btn-outline btn-sm"
                    download
                    onClick={(e) => e.stopPropagation()}
                  >
                    Download
                  </a>
                </div>
              </div>
            ))}
          </div>
        </section>

        <div className="examples-bottom-cta">
          <h3>Start creating your own puzzle book in minutes</h3>
          <div className="hero-buttons" style={{ justifyContent: "center" }}>
            <Link to="/create" className="btn btn-primary btn-lg">
              Create Your First Book
            </Link>
            <Link to="/play" className="btn btn-outline btn-lg">
              Play Online
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Examples;
