name: Deploy Backend to Hugging Face

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Hugging Face
        run: pip install huggingface_hub && python -c "from huggingface_hub import login; login('${{ secrets.HF_TOKEN }}')"
      - name: Clone Space
        run: git clone https://huggingface.co/spaces/muneer320/boop-backend ./hf-space
      - name: Copy files
        run: |
          cp -r backend/* ./hf-space/
          cd ./hf-space
          git config --global user.email "muneer.alam320@gmail.com"
          git config --global user.name "Muneer Alam"
          git add .
          git commit -m "Update from GitHub"
          git push